### PR TITLE
Switch to multistage build

### PR DESCRIPTION
**Pull request by jcoyne**
This reduces the size of the image from 567 MB to 263 MB and makes the build process more cacheable.

### CODE REVIEW

**Comment by justinlittman** [comment]
Can all of the Dockerfiles be combined into a single Dockerfile with multiple stages to avoid the whole docker-compose build dance?

Also, would like to work Dockerfile-dev into the mix to avoid it being completely separate from the prod build.

**Comment by jcoyne** [comment]
> Can all of the Dockerfiles be combined into a single Dockerfile with multiple stages to avoid the whole docker-compose build dance?
Do you know how to do that?  I'm not sure.
> Also, would like to work Dockerfile-dev into the mix to avoid it being completely separate from the prod build.

Can you do that in a different PR? As this isn't something I've been using, I don't understand how you want it to fit in.

**Comment by jcoyne** [comment]
After thinking about this for a minute, I think that joining into one Dockerfile would be less preferred, because now, I can just build the app, without having to rebuild the ruby or node image. If we put it in one file, the builds would take much longer.

**Comment by justinlittman** [comment]
Wouldn't they be cached? See, for example https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds

**Comment by jcoyne** [comment]
@justinlittman yes, but it still takes time to go through all the steps and determine if they've been cached.  If you just say "Start from this image" then it doesn't have to do that.

**Comment by jcoyne** [comment]
FWIW, I'm borrowing the approach that was demonstrated here: https://github.com/mikeantonelli/docker-rails-compose

**Pull request merged**
